---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-cloud
  namespace: cloud
  labels:
    app: cloud
    course: clo835
    Assignment: No.2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud
      name: cloud-pod
  template:
    metadata:
      labels:
        app: cloud
        name: cloud-pod
    spec:
      containers:
      - name: cloud-container
        image: 629376172886.dkr.ecr.us-east-1.amazonaws.com/cloud:v2.0