apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sun
  #app: sun
  labels:
    app: sun
    #name: sun
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: sun
      # name: sun
  template:
    metadata:
      labels:
        app: sun
        #name: sun
    spec:
      containers:
      - name: sun-container
        image: 629376172886.dkr.ecr.us-east-1.amazonaws.com/sun:v2.2
        ports:
        - containerPort: 80