apiVersion: apps/v1
kind: ReplicaSet
metadata:
  #app: cloud
  name: cloud
  labels:
    app: cloud
    # name: cloud
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      #name: cloud
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
        # name: cloud
    spec:
      containers:
      - name: cloud-container
        image: 629376172886.dkr.ecr.us-east-1.amazonaws.com/cloud:v2.2
        ports:
        - containerPort: 80