apiVersion: v1
kind: Service
metadata:
  #app: sun
  name: sun
  labels:
    app: sun
    #name: sun
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 8081
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30001
  selector:
    app: sun
    # name: sun